[app]
name = "HMTC"
description = "Harry Mack Track Creator"

[running]
log_level = "DEBUG"
download_on_init = false

[general]
environment="development"
items_per_page = 12
clean_downloads = false
minimum_section_size = 10

[paths]
storage = "/home/matt/apps/data_for_development/hmtc/development/storage"
working = "/home/matt/apps/data_for_development/hmtc/development/working"

[database]
name = "HMTCdevelopment"
host = "localhost"
user = "postgres"
password = "postgres"
port = 5432

[jellyfin]

prod_api = "44aadcfebc164ea7a80e67288ce7618b"
prod_password = "bizzle"
prod_url = "http://192.168.0.202:8095"
prod_user = "mizzle"
prod_user_id = "7a3d70b6fce444e1bcaf28a99e22a346"
prod_sources_library="Music Videos"
prod_tracks_library="HarryMackTracks"

api = "94c170f122df415297cf4ac3bd1430dc"
password = "user1"
url = "http://localhost:8096"
user = "user1"
user_id = "de68cdfc4f5842aaa7b56338a378a2a6"
sources_library="DownloadedVideos"
tracks_library="HarryMackTracks"



client="hmtc-dev"
device="cronus"
device_id="cronus-dev"
