[app]
name = "HMTC"
description = "Harry Mack Track Creator"

[running]
log_level = "DEBUG"

[general]
environment="staging"
items_per_page = 9
clean_downloads = false

[paths]
storage="/workspace/storageasdf"
working="/workspace/working"
logs="/workspace/logsqwer"

[database]
name = "HMTCstaging"
host = "docker-postgres-1"
user = "postgres"
password = "postgres"
port = 5432