[app]
name = "HMTC"
description = "Harry Mack Track Creator"

[running]
log_level = "DEBUG"
download_on_init = false

[general]
environment="development"
items_per_page = 12
clean_downloads = false
minimum_section_size = 10

[paths]
storage = "/home/matt/apps/data_for_development/hmtc/development/storage"
working = "/home/matt/apps/data_for_development/hmtc/development/working"

[database]
name = "HMTCdevelopment"
host = "localhost"
user = "postgres"
password = "postgres"
port = 5432

[jellyfin]
api = "d035af26e54542e9a3a31785ec260e14"
url = "http://192.168.0.202:8096"
user = "user1"
user_id = "f6f0fa8013a94ee3a1161bae8af59733"
password = "User1"
client="hmtc-dev"
device="cronus"
device_id="cronus-dev"
