[app]
name = "HMTC"
description = "Harry Mack Track Creator"

[running]
log_level = "DEBUG"
download_on_init = false

[general]
environment="testing"
items_per_page = 9
clean_downloads = false
minimum_section_size = 10

[paths]
storage = "/home/matt/apps/data_for_development/hmtc/testing/storage"
working = "/home/matt/apps/data_for_development/hmtc/testing/working"
logs = "/home/matt/apps/data_for_development/hmtc/testing/logs"

[database]
name = "HMTCtesting"
host = "127.0.0.1"
user = "postgres"
password = "postgres"
port = 5432

[jellyfin]
api = "d035af26e54542e9a3a31785ec260e14"
url = "http://192.168.0.202:8096"
user = "user1"
password = "User1"