##### only edit this once on the server

[app]
name = "HMTC"
description = "Harry Mack Track Creator"

[running]
log_level = "DEBUG"

[general]
environment="production"
items_per_page = 9
clean_downloads = false

[paths]
storage = "/workspace/storage"
working = "/workspace/working"

[database]
name = "HMTCproduction"
host = "192.168.0.202vcx"
user = "postgres"
password = "postgres"
port = 5432