version: '3'

services:
  app:
    # Using a Dockerfile is optional, but included for completeness.
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    volumes:
      - .:/workspace:cached
      - /home/matt/staging_data/storage:/workspace/storage
      - /home/matt/staging_data/working:/workspace/working
    environment:
      - ENVIRONMENT=${ENVIRONMENT}