version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@asdf.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - ~/apps/pgadmin4:/var/lib/pgadmin/
    depends_on: 
      - postgres


networks:
    default:
      name: myinternalnetwork
      external: true
      driver: bridge
