version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@asdf.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - ~/apps/pgadmin4:/var/lib/pgadmin/
    depends_on:
      - postgres

  redis:
    image: redis:7-bookworm
    ports:
      - 6379:6379

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ~/apps/jellyfin/config:/config
      - ~/apps/jellyfin/cache:/cache
      - type: bind
        source: ~/apps/data_for_development/jellyfin_libraries
        target: /media

    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery


networks:
  default:
    name: myinternalnetwork
    external: true
    driver: bridge
