services:
  app:
    container_name: hmtc-app
    build:
      context: .
      dockerfile: Dockerfile
      target: app-stage
    stop_signal: SIGINT
    ports:
      - 5000:5000
    volumes:
      - ~/apps/data_for_development/hmtc/staging/storage:/app/storage
      - ~/apps/data_for_development/hmtc/staging/working:/app/working
      - ~/apps/data_for_development/hmtc/staging/config:/app/config
    environment:
      - HMTC_ENV=staging
      - SOLARA_MODE=production
      - UV_HTTP_TIMEOUT=120000

networks:
  default:
    name: myinternalnetwork
    external: true
    driver: bridge
