version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@asdf.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - ~/apps/pgadmin4:/var/lib/pgadmin/
    depends_on:
      - postgres

  redis:
    image: redis:7-bookworm
    ports:
      - 6379:6379

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-stage
    entrypoint: celery
    command: -A hmtc.celery_app._celery worker --loglevel=info
    environment:
      - HMTC_ENV=development
    volumes:
      - ~/apps/worker:/app/worker
    links:
      - redis
    depends_on:
      - redis
