services:
  app:
    container_name: hmtc-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: app-stage
    stop_signal: SIGINT 
    ports:
      - 5000:5000
    volumes:
      - .:/workspace:cached
      - ~/apps/data_for_development/hmtc/staging/storage:/app/hmtc/storage
      - ~/apps/data_for_development/hmtc/staging/working:/app/hmtc/working
      - ~/apps/data_for_development/hmtc/staging/logs:/app/hmtc/logs
    environment:
      - HMTC_ENV=staging
      - HMTC_CONFIG_PATH=/app/hmtc/storage/config
      - UV_HTTP_TIMEOUT=120000


networks:
  default:
    name: myinternalnetwork
    external: true
