- url: https://www.youtube.com/watch?v=gBgJRYcIcWA
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: Can't Let YouTube Down | Harry Mack Omegle Bars 86
  ignore: false
- url: https://www.youtube.com/watch?v=6mfIBMQMYTw
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: He Bowed Down To This Freestyle | Harry Mack Omegle Bars 85
  ignore: false
- url: https://www.youtube.com/watch?v=16xwgMHig-A
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: I Don't Know What You're Talking About | Harry Mack Omegle Bars 83
  ignore: false
- url: https://www.youtube.com/watch?v=6Phbw1vg5Wc
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: This Is Unforgettable | Harry Mack Omegle Bars 82
  ignore: false
- url: https://www.youtube.com/watch?v=W03v-lUH8qQ
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: 'Harry Mack Live Chat Freestyle | Wordplay Wednesday #90'
  ignore: false
- url: https://www.youtube.com/watch?v=hZxiKDpribo
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: "\U0001F534LIVE: Harry Mack Freestyles Over DIRTY SOUTH Beats | Wordplay Wednesday #67"
  ignore: false
- url: https://www.youtube.com/watch?v=IULnhyDy4GQ
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: "\U0001F534LIVE: Harry Mack Freestyles Over DR. DRE Beats Round 2 | Stream of Consciousness #36"
  ignore: false
- url: https://www.youtube.com/watch?v=ZbIcmL6cuZk
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: "\U0001F534LIVE: Harry Mack Freestyles Over KANYE WEST Beats | Stream of Consciousness #25"
  ignore: false
- url: https://www.youtube.com/watch?v=IyYa-gTebrY
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: "\U0001F534LIVE: Harry Mack Freestyles Over Biggie Beats | Stream of Consciousness #22"
  ignore: false
- url: https://www.youtube.com/watch?v=SAMG0IIBWuo
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: I Promise... | Harry Mack EXCLUSIVE Guerrilla Bars
  ignore: false
- url: https://www.youtube.com/watch?v=x8QyqCgjV7Y
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: Ecstasy | Harry Mack x Beardyman Freestyle
  ignore: false
- url: https://www.youtube.com/watch?v=dKeS8l-JrBk
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: Aspirations Of A Freestyler | A Harry Mack Freestyle
  ignore: false
- url: https://www.youtube.com/watch?v=afOp4gKe00E
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: How To Cover Up Mistakes While Freestyling
  ignore: false
- url: https://www.youtube.com/watch?v=yANZNr2mkJU
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: 2 Ways to Free Associate While Freestyling
  ignore: false
- url: https://www.youtube.com/watch?v=MqRijCwXJL4
  album_name: NEED ALBUM NAME
  collection_name: NEED COLLECTION NAME OR USE ALBUM NAME BY DELETING
  video_title: The Setup Punchline Technique | Harry Mack x Steve-O
  ignore: false
