- url: https://www.youtube.com/watch?v=yrtXM2zzKo4
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=oqOPsX-A57Q
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=jbC-PXlBzjE
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=hZxiKDpribo
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=W03v-lUH8qQ
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=FBAaxCG00SE
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=81sr-Cn1IeE
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=STQ1U7ddGdk
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=1chrcjnRfi4
  album_name: ''
  collection_name: Guerrilla Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IyYa-gTebrY
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IyYa-gTebrY
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=ZbIcmL6cuZk
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=ZbIcmL6cuZk
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=iml3JBdmJyc
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=IULnhyDy4GQ
  album_name: ''
  collection_name: Stream of Consciousness
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=iP0z1X3hV7Q
  album_name: ''
  collection_name: Guerrilla Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=TVpDVtxI34w
  album_name: ''
  collection_name: Behind The Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=aIea7NWaJSY
  album_name: ''
  collection_name: Live Chat Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=d5c6y4qe5Yc
  album_name: ''
  collection_name: Guerrilla Bars Unreleased
  video_title: ''
  ignore: false
  date_added: 2023-01-09
- url: https://www.youtube.com/watch?v=5hlMLGAp4iw
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-19
- url: https://www.youtube.com/watch?v=Jsl-CTIkZ3M
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-19
- url: https://www.youtube.com/watch?v=bt0DLDPVE1M
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-20
- url: https://www.youtube.com/watch?v=6Phbw1vg5Wc
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-01-29
- url: https://www.youtube.com/watch?v=kEObMHgyjYc
  album_name: ''
  collection_name: Guerrilla Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-29
- url: https://www.youtube.com/watch?v=35WnTl616wU
  album_name: ''
  collection_name: Harry Mack Shorts
  video_title: ''
  ignore: false
  date_added: 2023-01-29
- url: https://www.youtube.com/watch?v=35WnTl616wU
  album_name: ''
  collection_name: Live Show Clips
  video_title: ''
  ignore: false
  date_added: 2023-01-29
- url: https://www.youtube.com/watch?v=16xwgMHig-A
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-02-11
- url: https://www.youtube.com/watch?v=5HVNp1-UWEQ
  album_name: ''
  collection_name: Guerrilla Bars
  video_title: ''
  ignore: false
  date_added: 2023-02-11
- url: https://www.youtube.com/watch?v=3gIzVwYSW4M
  album_name: ''
  collection_name: Guerrilla Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-11
- url: https://www.youtube.com/watch?v=tv7lm196h2M
  album_name: ''
  collection_name: Harry Mack Shorts
  video_title: ''
  ignore: false
  date_added: 2023-02-11
- url: https://www.youtube.com/watch?v=tv7lm196h2M
  album_name: ''
  collection_name: Live Show Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-11

- url: https://www.youtube.com/watch?v=5afTQOA8b2k
  album_name: ''
  collection_name: Guerrilla Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-16
- url: https://www.youtube.com/watch?v=8qsl5smWouc
  album_name: ''
  collection_name: Omegle Bars
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: https://www.youtube.com/watch?v=_NEb5WHY170
  album_name: ''
  collection_name: Omegle Bars Unreleased
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: https://www.youtube.com/watch?v=X33ND6vUG4k
  album_name: ''
  collection_name: Omegle Bars Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: https://www.youtube.com/watch?v=z0NWmAp8lfQ
  album_name: ''
  collection_name: Live Chat Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: https://www.youtube.com/watch?v=IL3_zdZl7nM
  album_name: ''
  collection_name: Happy Hour Clips
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: NA
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: NA
  album_name: ''
  collection_name: Wordplay Wednesday
  video_title: ''
  ignore: false
  date_added: 2023-02-22
- url: https://www.youtube.com/watch?v=IXbDPRRG948
  album_name: ''
  collection_name: Guerrilla Bars
  video_title: ''
  ignore: false
  date_added: 2023-04-03
- url: https://www.youtube.com/watch?v=4Gw89D50HrA
  album_name: ''
  collection_name: Busking With Bose
  video_title: ''
  ignore: false
  date_added: 2023-04-03
- url: https://www.youtube.com/watch?v=nAMoqBJJPMc
  album_name: ''
  collection_name: Live Show Clips
  video_title: ''
  ignore: false
  date_added: 2023-04-03
- url: https://www.youtube.com/watch?v=oln2F3iFHWs
  album_name: ''
  collection_name: Behind The Bars
  video_title: ''
  ignore: false
  date_added: 2023-04-03
- url: https://www.youtube.com/watch?v=dKeS8l-JrBk
  album_name: ''
  collection_name: Live Chat Clips
  video_title: ''
  ignore: false
  date_added: 2023-04-03
- url: https://www.youtube.com/watch?v=boNAB32Nsxc
  album_name: ''
  collection_name: Guerrilla Bars Unreleased
  video_title: ''
  ignore: false
  date_added: 2023-04-10
- url: https://www.youtube.com/watch?v=1SHsGFXvtB8
  album_name: ''
  collection_name: Harry Mack Shorts
  video_title: ''
  ignore: false
  date_added: 2023-04-10
